language: node_js
node_js:
- stable
cache: yarn
install:
- yarn
jobs:
  include:
  - stage: Build and test
    script:
    - yarn ci
  - stage: Release package
    if: branch = master
    script: yarn build
    deploy:
      edge: true
      provider: npm
      email: alfonz@homolik.cz
      api_key:
        secure: CRkReRFQKZo0tn+fGMhFc+Ltm7d/irRPLW64jNi7Z/1oJ1Qtmpya/ItjYlVZ0xssdJUyMiARYpX66NuRGEJ+Qh94j470JUqxzmDTdsZqWqdaGs5S/Mt0CcZQAmGC2zQ5cxm9TOK/n1z2F+U0y1HNpqmCUiQUGzEPEEk+8CwOAJ+8Z9j1AHRQFlH3dkvbh4eqJqj2fpnsWrOlP/Pgr7pBJB/Mu2bckG1Y3Scb+8LPEwdzbtQfsGWZVQapZNXY4zzqb1Gv+MCDprWbySd47VXmR2ZW9v6gZ2rqzvPQyxq70CiTcRhdotLzc0J1icW1HgI9lRL4WncTu2pCq5wQdDVysBg09/TfDlUSoOFFGjIvZUs9UsEDt0wSr7unN/Gni2ud17Rq8cQYzOa3p2qf7pmix1yS3EJGtHFrz3BLeRKg/D6N36pmRWLwqdn6rlK4+wvnbW7Jl76LwBiXg9d45Ftx3HkAMYB2HK1j5G+iEovEFCl4ZARA+2y4Xg6cAOmrrEv5uFK5j5b4w5vUl4DTEEZRjua4TAcwqubja+aNzOykKAf4+hlpZSPGjABoGB18sFpW+b/m3NdRNtUVR2Ka4bMAYeIU90Zi/WSYOqNJCBkfJl1WHZmKna079kr/iFIQQH783OeYmnS4uIGIylguA5qc/90oju/QAgtLRcT/oANJpcg=
      skip_cleanup: true

